### ISSUE TITLE
Questions on the competition

### ISSUE THREAD

**Issue by marlvernchimbwanda** [olive-robotics/bots_bento_icra24#1]
1. Do we get a map? Can we map?
2. Can we knock other KLTs as we go?
3. Can we cover the april tags as our technical challenge?
4. Will we be given the locations of the april tags on the KLTs? Or will they at least be symmetrically placed?
5. Do the floor tags have unique IDs from one another

@cxdcxd @arn3r05t

**Comment by cxdcxd** [comment]
Do we get a map? Can we map?

You will not get any map. Yes you can map the environment during the test run. But the KLT's will be placed randomly and you dont know the place of them.

Can we knock other KLTs as we go?

Yes, up to the point that you don't damage the robot.

Can we cover the april tags as our technical challenge?

Yes.

Will we be given the locations of the april tags on the KLTs? Or will they at least be symmetrically placed?

It will be symmetrically placed and it will be standard on all of them.

Do the floor tags have unique IDs from one another

Yes, we will put different id numbers and also give you the numbers in advance so you can use it for robot odometry and localization.

**Comment by leon-seidel** [comment]
Is it still planned that the Apriltag code on the KLTs will be the same as the tag codes of their goal box on the ground? If the tags on the KLTs will be smaller than the tags on the ground this would probably require changes in standard Apriltag libraries, as tag localisation only works for each tag code having a consistent size.

**Comment by cxdcxd** [comment]
We have two sizes of tags: 10cm and 20cm. It's clear that we'll use the smaller 10cm tags for KLT and the larger ones for ground.

**Comment by leon-seidel** [comment]
Thanks! Will the same tag code, for example 36h11_42, be used for both on the ground and on a KLT?

**Comment by cxdcxd** [comment]
Yes.

**Comment by cxdcxd** [comment]
https://github.com/rgov/apriltag-pdfs/tree/main/tag36h11/a4
