### ISSUE TITLE
Fisheye FOV | Motor torque mode | Hook design

### ISSUE THREAD

**Issue by Rudresh172** [olive-robotics/bots_bento_icra24#2]
1. Will there be an option to use the fisheye lens on the camera (1.8 mm)? If yes, what is the FOV of the fisheye lens camera setup? How reliable are the rectified images according to your previous testing?

2. What function does the ROS service '/setTorqueEnable' provide? Does it enable us to view the torque applied by the motor at that instant or does it give command to the motor to apply the specified torque?

3. If we design a custom hook for the KLT, can we fit those 3d printed hooks to all the 6 KLTs during our run?

**Comment by cxdcxd** [comment]
1) Will there be an option to use the fisheye lens on the camera (1.8 mm)? If yes, what is the FOV of the fisheye lens camera setup? How reliable are the rectified images according to your previous testing?

Yes, you can use the fisheye. I will update the different lens specifications in the Rulebook asap.

2) What function does the ROS service '/setTorqueEnable' provide? Does it enable us to view the torque applied by the motor at that instant or does it give command to the motor to apply the specified torque?

It is only useful for position mode servo motor. It is only an enabler of the torque to the motor. You have to call it first then you can send goal position via the topic. Its like a emergency switch to cut the power. 

3) If we design a custom hook for the KLT, can we fit those 3d printed hooks to all the 6 KLTs during our run?

The idea of the competition is to not touch the KLTs and you can't customize them by installing aditional parts. You can use this idea for the open challenge part only.

**Comment by Rudresh172** [comment]
Thanks for the clarification! We have some additional questions - 

4. There seems to be conflicting information regarding the AR tag on KLTs. 
Section 3.2.8 states - 
```
To facilitate identification and sorting, each KLT is equipped with an April Tag on both its front and back sides. These tags contain unique IDs, enabling the robot to accurately recognize and handle the KLTs according to the competition's requirements.
```

Section 3.2.8.1 states - 
```
2x April Tags will be installed on each side and on each KLT. In this example for two KLT it will be 16 Tags. The id for all Tags will be same and you can identify the side or front from distance between each April Tag.
```

5. Will this L-shaped mount be also provided to us or do we need to arrange for it ourselves?
![image](https://github.com/olive-robotics/bots_bento_icra24/assets/93994789/707752f2-fd6a-4dc0-a132-e3410de4140e)

**Comment by cxdcxd** [comment]
4) It is now more clear and is corrected. Thanks.
5) Yes, i have updated the component list too.

**Comment by Rudresh172** [comment]
Hey @cxdcxd,

6. The Maker kit contains 6mm square headed MakerBeam bolts. Do we have more options for bolts for a custom camera mount? More length options would be highly appreciated since 3d printed parts might need some thickness to have enough strength.

**Comment by cxdcxd** [comment]
You can bring any type of passive parts or screws and change things in a way you like. We will only give you the list we explained and the example base robot. Rest you can change in a way you like.

**Comment by flerovious** [comment]
Are we provided with the supported lens mentioned here, including the fisheye lens?
https://github.com/olive-robotics/bots_bento_icra24/blob/main/docs/rulebook.md#supported-camera-lenses

**Comment by cxdcxd** [comment]
Yes, we will provide additional lenses so you can switch them out depending on the needs of your application.
