### ISSUE TITLE
Number of Servos

### ISSUE THREAD

**Issue by maychristopher** [olive-robotics/bots_bento_icra24#3]
How many servos can / must we use?

The component list states five, the overview image shows six.
The latter is also stated by "To enhance its capabilities, you are tasked with creatively installing an additional 2 cameras and 2 actuators."

**Comment by cxdcxd** [comment]
For sure 5 is fixed. But one is more like a backup. Depends on the situation and paricipents it can change to 6. But 5 is the official number of servos.

**Comment by maychristopher** [comment]
Ok, thank you,
