### ISSUE TITLE
ROS Humble and Motors

### ISSUE THREAD

**Issue by Kevinpaulose05** [olive-robotics/bots_bento_icra24#5]
1. Do we necessarily need ROS Humble (Ubuntu 22.04) to run the components provided or will ROS Foxy (Ubuntu 20.04) work? We are currently using Ubuntu 20.04 ROS Foxy. Should we switch?

2. It is mentioned that we will be given four motors for the wheel, and one motor for the hook (five in total). Is there a sixth motor provided for the camera? It is mentioned that 2 actuators and 2 cameras are provided. Please provide some clarity about these motors and actuators.

**Comment by cxdcxd** [comment]
Do we necessarily need ROS Humble (Ubuntu 22.04) to run the components provided or will ROS Foxy (Ubuntu 20.04) work? We are currently using Ubuntu 20.04 ROS Foxy. Should we switch?

It will work but to maximize compatibility and ensure we will not have unpredicted behaviors it is better to upgrade everything to Ubuntu 22.04 and ROS Humble.

It is mentioned that we will be given four motors for the wheel, and one motor for the hook (five in total). Is there a sixth motor provided for the camera? It is mentioned that 2 actuators and 2 cameras are provided. Please provide some clarity about these motors and actuators.

The official amount of the motors are 5 , which 4 you will use for the base and 1 for the hook. But yes you will have 1 more motor but that is backup. We should decide later that if you can use that also for the robot. Now consider you have 5 motors.

**Comment by Kevinpaulose05** [comment]
Understood. Thanks!
