### ISSUE TITLE
Production Members

### ISSUE THREAD

**Issue by AyumuIwa** [olive-robotics/bots_bento_icra24#6]
Greetings,

Is it possible to have friends who are not team members but will be at the event to help with production during the event?Is it forbidden for outsiders to support a particular team?

Thank you.

**Comment by cxdcxd** [comment]
Unfortunately, inviting friends or additional individuals to join and assist during the event is not permissible. Only officially registered members are permitted to participate and collaborate within the teams.

**Comment by AyumuIwa** [comment]
Understood. Thanks!
