### ISSUE TITLE
Query Regarding AR Tags on the floor

### ISSUE THREAD

**Issue by Spartan-Velanjeri** [olive-robotics/bots_bento_icra24#8]
Greetings,

We wanted to know if the tags on the floor are all unique meaning each of them having a different ID, as that would be useful for us.

Thank you !

**Comment by cxdcxd** [comment]
The tags for KLT is same id per KLT. Example if it has 8 tags for all sides, they will be same. IDs for KLT will be 1 to 6. But for ground we will count from  id 100 to 125. 5x5 grid.

**Comment by leon-seidel** [comment]
With a 5x5 grid and 6 KLTs, how will the designated parking spot for each KLT correspond to the KLT tags?

**Comment by cxdcxd** [comment]
we have 6 park zones. The general idea is you have to park the correct ID klt in the correct parking zone. The ground Tags are for localization. I will explain better in the Tag section asap.

**Comment by leon-seidel** [comment]
Any updates on this @cxdcxd?

**Comment by cxdcxd** [comment]
Please check announcement 3 on the repoo. We uploaded the complete ROS 2 bag from a real experiment. In addition the final tags which we will use during bots and bento is now uploaded in the tags folder.

**Comment by cxdcxd** [comment]
KLT will keep same id on each side starting from 1,2,3,4,5,6. Ground will be a grid of tags each 1 meter and ID starting from 101.
