### ISSUE TITLE
Use of hardware for technical challenge

### ISSUE THREAD

**Issue by flerovious** [olive-robotics/bots_bento_icra24#9]
I'd like to confirm the hardware limitations for the technical challenge portion of the competition. According to the rules listed [here](https://github.com/olive-robotics/bots_bento_icra24/blob/main/docs/rulebook.md#312-given-robotic-components), are we restricted to using only the provided robotic components? Specifically, are we prohibited from using additional equipment such as lidar or extra cameras for the technical challenge?

**Comment by cxdcxd** [comment]
Yes, you can use any kind of hardware, sensor to use during technical challenge.

But for the main part you cannot use additional sensors, actuators. You can just use any custom computing unit. You have to consider the power source as well.
